### ISSUE TITLE
[QUESTION] Content Update for new tool Microsoft Todo

### ISSUE THREAD

**Issue by AndreSchiemann** [pnp/custom-learning-office-365#675]
### What is the context of your question

- [ ] Installation
- [] **Learning Pathways Content**
- [ ] SharePoint Success Content
- [ ] Administration
- [ ] Custom Content
- [ ] Viewer Web Part

### What is your question
In our pathways solution the Tool "Microsoft Todo" does not show up in the content even there is content available for Microsoft Todo: (URL for content related to Microsoft Todo https://support.microsoft.com/en-gb/todo# )

Is the help content for Microsoft Todo already included in the Content Pack on the CDN server!?

How I can ensure/verifiy, that our Learning Pathways installation retrieves the newest content from support.microsoft.com?
Our CDN key is configured to:

![lp_cdn_key_config](https://user-images.githubusercontent.com/76996358/174723121-875e4422-f8da-48cd-adcb-100f39e1adac.PNG)

**Comment by v-ashrirao** [comment]
@AndreSchiemann, Thank you for reporting this. Please allow us some time, we will get back to you ASAP.

**Comment by dcashpeterson** [comment]
@AndreSchiemann There is currently no content in Microsoft 365 learning pathways for Microsoft ToDo. The content in learning pathways is a curated list of content and not a replication of support.microsoft.com or docs.microsoft.com. You are using the default CDN so whenever we push out a new update to the content you should have the latest. I will refer that as a request to the content team. Thanks for using Microsoft 365 learning pathways.

**Comment by AndreSchiemann** [comment]
@dcashpeterson Many thanks for your reply!

In my opinion the value of the Microsoft 365 learning pathways is highly dependent on the freshness and therefore the update cycle by the content team for new content from support.microsoft.com or docs.microsoft.com.

The current sitution is not sufficient enough for a real world scenario, where Microsoft Todo is in the field since "ages"/months and official support content (like https://support.microsoft.com/en-gb/todo#) is already available.

IMHO there is a need for an mechanism, which ensure that most recent content from both official websites get automatically added into the default CDN of LP. Alternativly the community need the possibility/ability to support the content team and add/enhance the prebuilt categories/playlists with hyperlinks to support.microsoft.com or docs.microsoft.com in the default CDN.

In the current state of learning pathways I cannot recommend it as sufficient learning/adoption solution to my customers because of lack of most recent M365 services. Viva Learning is also not sufficient in the current feature level/state. 👎 

BR,
André

**Comment by dcashpeterson** [comment]
@AndreSchiemann I understand your concerns and will relay them to the content team. We do our best to update the content on a quarterly basis but have hit some challenges in that arena as of late. We have a new update with Viva content coming out shortly. 

You do have the ability to add your own custom content either as a custom playlist/assets and include content you find from support and docs however there is an issue where some of that content does not allow itself to be shown in an Iframe. You can also create a custom content pack for you or your clients if you want more control over what goes in and what doesn't. 

Regards,
Derek
